---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Params.rolebindingName }}
  namespace: {{ .Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Params.rolebindingClusterRoleKind }}
  name: {{ .Params.rolebindingClusterRoleName }}
subjects:
- kind: {{ .Params.rolebindingSubjectKind }}
  name: {{ .Name }}-sa
  namespace: {{ .Namespace }}
